### ISSUE TITLE
.ply to .bin Lidar format

### ISSUE THREAD

**Issue by gsus24** [john-davies/lidar-ply#1]
Hello
i want to analyze Lidar sensor data in .bin format and can generate .ply format out of a simulation. 
Is there a chance to convert Ply2Lidar(.bin)? Hope you can get help me started.
Thanks and best regards

**Comment by john-davies** [comment]
I'm afraid that I need some more information before I can answer your question. 

- What format is your input ( .bin ) data?
- I found this online - https://en.wikipedia.org/wiki/LAS_file_format. Is this the format that you're referring to? If not is there a specification of the format of the data?
- Do you have a small, simple example?

lidar2ply is designed to convert LiDAR data supplied in Esri ASCII grid format ( https://en.wikipedia.org/wiki/Esri_grid ) but as long as you know the format of your data then it should be possible to adapt the program to process it.

**Comment by gsus24** [comment]
The input .bin data is vendor specific and disclosed. But there is a framework to read raw Data from Lidar sensors, decode it and parse the data. Like i understand i could build my own plugin but instead of read raw Data from sensor and decode it, i need read the .ply files.

The are two variables: LidarPointXYZI and LidarPointRTHI
XYZ are the coordinates. What could be RTHI? Alignment or the vector of the direction the points are moving?
The rest variables to parse the Data are sensor and host timestamp or maximum number of points per spin and per scan.

Hope you have an idea on read the .ply file and get XYZ and RTH of the point cloud?

**Comment by john-davies** [comment]
Reading a PLY file to get the XYZ coordinates of the points ( or verticies ) is relatively straightforward. There's a good description of the specification here - http://paulbourke.net/dataformats/ply/. The code for the `plymenu` program in this repository will read a PLY file in both ascii and binary formats and allow you to manipulate the values. I'm afraid that I have no idea what "RTH" refers to in this context and a Google search doesn't come up with anything either.

A couple of questions:

- Do you have an example of the PLY file output?
- If so, have you tried opening that file in [Meshlab](https://www.meshlab.net/) ( or somthing similar )

**Comment by john-davies** [comment]
As there has been no further response for 6 weeks then I'm closing this issue.
